name: dadapush_client
homepage: https://www.dadapush.com
version: 1.0.0
description: DaDaPush Client For Dart
author: DaDaPush.com <contacts@dadapush.com>
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: '>=0.11.1 <0.13.0'
dev_dependencies:
  test: ^1.3.0
